### PR TITLE
PHP7 update

### PR DESCRIPTION
**Pull request by mambax7**
using: https://github.com/lmc-eu/php-coding-standard

### CODE REVIEW

**Comment by cliffhall** [comment]
Hi Michael,

Thanks for the PR. Not being a PHP person myself, my first question is: what are the implications of this update. Will it fail on prior versions of PHP? Does it use any whiz-bang new language features that would cause a breaking change, that aren't necessary?

Cheers,
-=Cliff>

**Comment by mambax7** [comment]
The current version has errors on PHP 7. 
The submitted one in PR runs without problems on PHP 5.6+ and PHP 7.0 - 7.2.8, which are the officially supported PHP versions currently. 

There are no whiz-bang new language features added :)

**Comment by cliffhall** [comment]
Thanks, Michael. And do the unit tests at https://github.com/PureMVC/puremvc-php-standard-unittests all work with the new version?

**Comment by mambax7** [comment]
I have to admit  that I didn't run the test, I only ran the Zen Garden demo, and all the themes worked perfectly there, so obviously nothing was broken.  But this was expected, because I didn't introduce any new features, only adjusted some deprecated/obsolete language changes, to make it compatible with PHP 7

**Comment by cliffhall** [comment]
Since you're more readily able to wrangle PHP than I, would you mind running those tests? There's no guarantee that every test case we've identified in the suite is actually exercised in Zen Garden.

**Comment by mambax7** [comment]
I ran the test and there was an old problem with "Array to string conversion" but I guess, the previous PHP versions didn't complain about it.  It is now fixed, and all the tests passed without a failure. 
And somehow I've missed last time an old constructor, so I fixed that as well.

**Comment by cliffhall** [comment]
Excellent. Thanks for that. Merging now...

**Comment by cliffhall** [comment]
Oh, hey, one extra thing, would you mind amending the README.md and VERSION files, bumping the version number to 1.1.0 with a comment about the update to PHP 7, and also adding your email as an author? You'll need to pull the upstream and make another PR.

**Comment by mambax7** [comment]
Done

**Pull request merged**
